-- SpendLens Supabase schema
-- Run this in the Supabase SQL editor for your project.

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  description text,
  amount numeric(10,2) not null,
  category text not null,
  expense_date date not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  receipt_path text,
  receipt_original_name text,
  receipt_uploaded_at timestamptz
);

create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  category text,
  month text not null,
  amount numeric(10,2) not null,
  threshold_percent int default 80,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, month, category)
);

create table if not exists public.recurring_expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  description text,
  amount numeric(10,2) not null,
  category text not null,
  frequency text not null,
  day_of_month int,
  day_of_week int,
  next_run_date date not null,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.expenses enable row level security;
alter table public.budgets enable row level security;
alter table public.recurring_expenses enable row level security;

create policy "expenses_select_own" on public.expenses
  for select using (auth.uid() = user_id);
create policy "expenses_insert_own" on public.expenses
  for insert with check (auth.uid() = user_id);
create policy "expenses_update_own" on public.expenses
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "expenses_delete_own" on public.expenses
  for delete using (auth.uid() = user_id);

create policy "budgets_select_own" on public.budgets
  for select using (auth.uid() = user_id);
create policy "budgets_insert_own" on public.budgets
  for insert with check (auth.uid() = user_id);
create policy "budgets_update_own" on public.budgets
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "budgets_delete_own" on public.budgets
  for delete using (auth.uid() = user_id);

create policy "recurring_select_own" on public.recurring_expenses
  for select using (auth.uid() = user_id);
create policy "recurring_insert_own" on public.recurring_expenses
  for insert with check (auth.uid() = user_id);
create policy "recurring_update_own" on public.recurring_expenses
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "recurring_delete_own" on public.recurring_expenses
  for delete using (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', false)
on conflict (id) do nothing;

create policy "receipts_read_own" on storage.objects
  for select using (
    bucket_id = 'receipts'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
create policy "receipts_insert_own" on storage.objects
  for insert with check (
    bucket_id = 'receipts'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
create policy "receipts_update_own" on storage.objects
  for update using (
    bucket_id = 'receipts'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
create policy "receipts_delete_own" on storage.objects
  for delete using (
    bucket_id = 'receipts'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
